-- FiguMatch initial schema
-- Tables: profiles, figuritas, matches, kioscos, intercambios
-- Triggers: auto profile creation on signup + updated_at maintenance

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Shared updated_at trigger function
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
	new.updated_at = now();
	return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- profiles
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
	id uuid primary key references auth.users(id) on delete cascade,
	email text not null unique,
	nombre text,
	reputacion integer not null default 0 check (reputacion >= 0 and reputacion <= 5),
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- figuritas
-- ---------------------------------------------------------------------------
create table if not exists public.figuritas (
	id bigint generated by default as identity primary key,
	user_id uuid not null references auth.users(id) on delete cascade,
	numero integer not null check (numero >= 1 and numero <= 678),
	tipo text not null check (tipo in ('repetida', 'faltante')),
	nombre_jugador text,
	imagen_url text,
	seleccion text,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- matches
-- ---------------------------------------------------------------------------
create table if not exists public.matches (
	id bigint generated by default as identity primary key,
	user_a uuid not null references auth.users(id) on delete cascade,
	user_b uuid not null references auth.users(id) on delete cascade,
	figurita_a_id bigint not null references public.figuritas(id) on delete cascade,
	figurita_b_id bigint not null references public.figuritas(id) on delete cascade,
	tipo text not null default 'doble' check (tipo in ('doble', 'simple')),
	estado text not null default 'pendiente' check (estado in ('pendiente', 'aceptado', 'cancelado', 'completado')),
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	check (user_a <> user_b)
);

-- ---------------------------------------------------------------------------
-- kioscos
-- ---------------------------------------------------------------------------
create table if not exists public.kioscos (
	id bigint generated by default as identity primary key,
	nombre text not null,
	direccion text not null,
	latitud double precision not null,
	longitud double precision not null,
	activo boolean not null default true,
	created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- intercambios
-- ---------------------------------------------------------------------------
create table if not exists public.intercambios (
	id bigint generated by default as identity primary key,
	match_id bigint not null references public.matches(id) on delete cascade,
	kiosco_id bigint not null references public.kioscos(id) on delete restrict,
	codigo text not null unique,
	estado text not null default 'pendiente' check (estado in ('pendiente', 'retirado', 'expirado', 'cancelado')),
	fecha_expiracion timestamptz,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Trigger: auto-create profile when a new auth user signs up
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
	insert into public.profiles (id, email, nombre)
	values (
		new.id,
		coalesce(new.email, ''),
		coalesce(
			new.raw_user_meta_data ->> 'nombre',
			new.raw_user_meta_data ->> 'full_name',
			new.raw_user_meta_data ->> 'name',
			split_part(coalesce(new.email, ''), '@', 1)
		)
	)
	on conflict (id) do nothing;

	return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute procedure public.handle_new_user();

-- ---------------------------------------------------------------------------
-- updated_at triggers
-- ---------------------------------------------------------------------------
drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute procedure public.set_updated_at();

drop trigger if exists set_figuritas_updated_at on public.figuritas;
create trigger set_figuritas_updated_at
before update on public.figuritas
for each row
execute procedure public.set_updated_at();

drop trigger if exists set_matches_updated_at on public.matches;
create trigger set_matches_updated_at
before update on public.matches
for each row
execute procedure public.set_updated_at();

drop trigger if exists set_intercambios_updated_at on public.intercambios;
create trigger set_intercambios_updated_at
before update on public.intercambios
for each row
execute procedure public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Optional helper for anonymous-safe figuritas listing
-- ---------------------------------------------------------------------------
create or replace function public.get_anonymous_figuritas()
returns table (
	id bigint,
	numero integer,
	tipo text,
	nombre_jugador text,
	imagen_url text,
	seleccion text,
	created_at timestamptz
)
language sql
security definer
set search_path = public
as $$
	select f.id, f.numero, f.tipo, f.nombre_jugador, f.imagen_url, f.seleccion, f.created_at
	from public.figuritas f
	where auth.uid() is not null
		and f.user_id <> auth.uid();
$$;

revoke all on function public.get_anonymous_figuritas() from public;
grant execute on function public.get_anonymous_figuritas() to authenticated;

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.profiles enable row level security;
alter table public.figuritas enable row level security;
alter table public.matches enable row level security;
alter table public.kioscos enable row level security;
alter table public.intercambios enable row level security;

-- profiles
drop policy if exists "Profiles can view own" on public.profiles;
create policy "Profiles can view own"
on public.profiles
for select
to authenticated
using (id = auth.uid());

drop policy if exists "Profiles can update own" on public.profiles;
create policy "Profiles can update own"
on public.profiles
for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

-- figuritas
drop policy if exists "Users can view own figuritas" on public.figuritas;
create policy "Users can view own figuritas"
on public.figuritas
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "Users can insert own figuritas" on public.figuritas;
create policy "Users can insert own figuritas"
on public.figuritas
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "Users can update own figuritas" on public.figuritas;
create policy "Users can update own figuritas"
on public.figuritas
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "Users can delete own figuritas" on public.figuritas;
create policy "Users can delete own figuritas"
on public.figuritas
for delete
to authenticated
using (user_id = auth.uid());

-- matches
drop policy if exists "Users can view their matches" on public.matches;
create policy "Users can view their matches"
on public.matches
for select
to authenticated
using (user_a = auth.uid() or user_b = auth.uid());

drop policy if exists "Users can create matches where they participate" on public.matches;
create policy "Users can create matches where they participate"
on public.matches
for insert
to authenticated
with check (user_a = auth.uid() or user_b = auth.uid());

drop policy if exists "Users can update their matches" on public.matches;
create policy "Users can update their matches"
on public.matches
for update
to authenticated
using (user_a = auth.uid() or user_b = auth.uid())
with check (user_a = auth.uid() or user_b = auth.uid());

-- kioscos
drop policy if exists "Anyone authenticated can view kioscos" on public.kioscos;
create policy "Anyone authenticated can view kioscos"
on public.kioscos
for select
to authenticated
using (true);

-- intercambios
drop policy if exists "Users can view intercambios from their matches" on public.intercambios;
create policy "Users can view intercambios from their matches"
on public.intercambios
for select
to authenticated
using (
	exists (
		select 1
		from public.matches m
		where m.id = intercambios.match_id
			and (m.user_a = auth.uid() or m.user_b = auth.uid())
	)
);

drop policy if exists "Users can create intercambios from their matches" on public.intercambios;
create policy "Users can create intercambios from their matches"
on public.intercambios
for insert
to authenticated
with check (
	exists (
		select 1
		from public.matches m
		where m.id = intercambios.match_id
			and (m.user_a = auth.uid() or m.user_b = auth.uid())
	)
);

drop policy if exists "Users can update intercambios from their matches" on public.intercambios;
create policy "Users can update intercambios from their matches"
on public.intercambios
for update
to authenticated
using (
	exists (
		select 1
		from public.matches m
		where m.id = intercambios.match_id
			and (m.user_a = auth.uid() or m.user_b = auth.uid())
	)
)
with check (
	exists (
		select 1
		from public.matches m
		where m.id = intercambios.match_id
			and (m.user_a = auth.uid() or m.user_b = auth.uid())
	)
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
create index if not exists idx_figuritas_user_id on public.figuritas(user_id);
create index if not exists idx_figuritas_numero on public.figuritas(numero);
create index if not exists idx_matches_user_a on public.matches(user_a);
create index if not exists idx_matches_user_b on public.matches(user_b);
create index if not exists idx_intercambios_match_id on public.intercambios(match_id);
create index if not exists idx_intercambios_kiosco_id on public.intercambios(kiosco_id);

-- ---------------------------------------------------------------------------
-- MVP seed for kioscos (Catamarca)
-- ---------------------------------------------------------------------------
insert into public.kioscos (nombre, direccion, latitud, longitud, activo)
values
	('Kiosco San Cayetano', 'Av. Virgen del Valle 350, San Fernando del Valle', -28.4686, -65.7795, true),
	('Kiosco La Esquina', 'Salta 920, San Fernando del Valle', -28.4699, -65.7859, true),
	('Kiosco Plaza', 'Rivadavia 650, San Fernando del Valle', -28.4662, -65.7791, true)
on conflict do nothing;

