-- FiguMatch initial schema (corregido: figuritas.id uuid)
-- Tables: profiles, figuritas, matches, kioscos, intercambios
-- Triggers: auto profile creation on signup + updated_at maintenance

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Shared updated_at trigger function
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
	new.updated_at = now();
	return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- profiles
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
	id uuid primary key references auth.users(id) on delete cascade,
	email text not null unique,
	nombre text,
	reputacion integer not null default 0 check (reputacion >= 0 and reputacion <= 5),
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- figuritas (ID uuid)
-- ---------------------------------------------------------------------------
create table if not exists public.figuritas (
	id uuid default gen_random_uuid() primary key,
	user_id uuid not null references auth.users(id) on delete cascade,
	numero integer not null check (numero >= 1 and numero <= 678),
	tipo text not null check (tipo in ('repetida', 'faltante')),
	nombre_jugador text,
	imagen_url text,
	seleccion text,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- matches (figurita IDs uuid)
-- ---------------------------------------------------------------------------
create table if not exists public.matches (
	id bigint generated by default as identity primary key,
	user_a uuid not null references auth.users(id) on delete cascade,
	user_b uuid not null references auth.users(id) on delete cascade,
	figurita_a_id uuid not null references public.figuritas(id) on delete cascade,
	figurita_b_id uuid not null references public.figuritas(id) on delete cascade,
	tipo text not null default 'doble' check (tipo in ('doble', 'simple')),
	estado text not null default 'pendiente' check (estado in ('pendiente', 'aceptado', 'cancelado', 'completado')),
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	check (user_a <> user_b)
);

-- ---------------------------------------------------------------------------
-- kioscos
-- ---------------------------------------------------------------------------
create table if not exists public.kioscos (
	id bigint generated by default as identity primary key,
	nombre text not null,
	direccion text not null,
	latitud double precision not null,
	longitud double precision not null,
	activo boolean not null default true,
	created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- intercambios
-- ---------------------------------------------------------------------------
create table if not exists public.intercambios (
	id bigint generated by default as identity primary key,
	match_id bigint not null references public.matches(id) on delete cascade,
	kiosco_id bigint not null references public.kioscos(id) on delete restrict,
	codigo text not null unique,
	estado text not null default 'pendiente' check (estado in ('pendiente', 'retirado', 'expirado', 'cancelado')),
	fecha_expiracion timestamptz,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Trigger: auto-create profile when a new auth user signs up
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
	insert into public.profiles (id, email, nombre)
	values (
		new.id,
		coalesce(new.email, ''),
		coalesce(
			new.raw_user_meta_data ->> 'nombre',
			new.raw_user_meta_data ->> 'full_name',
			new.raw_user_meta_data ->> 'name',
			split_part(coalesce(new.email, ''), '@', 1)
		)
	)
	on conflict (id) do nothing;

	return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute procedure public.handle_new_user();

-- ---------------------------------------------------------------------------
-- updated_at triggers
-- ---------------------------------------------------------------------------
drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute procedure public.set_updated_at();

drop trigger if exists set_figuritas_updated_at on public.figuritas;
create trigger set_figuritas_updated_at
before update on public.figuritas
for each row
execute procedure public.set_updated_at();

drop trigger if exists set_matches_updated_at on public.matches;
create trigger set_matches_updated_at
before update on public.matches
for each row
execute procedure public.set_updated_at();

drop trigger if exists set_intercambios_updated_at on public.intercambios;
create trigger set_intercambios_updated_at
before update on public.intercambios
for each row
execute procedure public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Helper for anonymous-safe figuritas listing (id uuid)
-- ---------------------------------------------------------------------------
drop function if exists public.get_anonymous_figuritas();
create or replace function public.get_anonymous_figuritas()
returns table (
	id uuid,
	numero integer,
	tipo text,
	nombre_jugador text,
	imagen_url text,
	seleccion text,
	created_at timestamptz
)
language sql
security definer
set search_path = public
as $$
	select f.id, f.numero, f.tipo, f.nombre_jugador, f.imagen_url, f.seleccion, f.created_at
	from public.figuritas f
	where auth.uid() is not null
		and f.user_id <> auth.uid();
$$;

revoke all on function public.get_anonymous_figuritas() from public;
grant execute on function public.get_anonymous_figuritas() to authenticated;

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.profiles enable row level security;
alter table public.figuritas enable row level security;
alter table public.matches enable row level security;
alter table public.kioscos enable row level security;
alter table public.intercambios enable row level security;

-- profiles
drop policy if exists "Profiles can view own" on public.profiles;
create policy "Profiles can view own"
on public.profiles
for select
to authenticated
using (id = auth.uid());

drop policy if exists "Profiles can update own" on public.profiles;
create policy "Profiles can update own"
on public.profiles
for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

-- figuritas
drop policy if exists "Users can view own figuritas" on public.figuritas;
create policy "Users can view own figuritas"
on public.figuritas
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "Users can insert own figuritas" on public.figuritas;
create policy "Users can insert own figuritas"
on public.figuritas
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "Users can update own figuritas" on public.figuritas;
create policy "Users can update own figuritas"
on public.figuritas
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "Users can delete own figuritas" on public.figuritas;
create policy "Users can delete own figuritas"
on public.figuritas
for delete
to authenticated
using (user_id = auth.uid());

-- matches
drop policy if exists "Users can view their matches" on public.matches;
create policy "Users can view their matches"
on public.matches
for select
to authenticated
using (user_a = auth.uid() or user_b = auth.uid());

drop policy if exists "Users can create matches where they participate" on public.matches;
create policy "Users can create matches where they participate"
on public.matches
for insert
to authenticated
with check (user_a = auth.uid() or user_b = auth.uid());

drop policy if exists "Users can update their matches" on public.matches;
create policy "Users can update their matches"
on public.matches
for update
to authenticated
using (user_a = auth.uid() or user_b = auth.uid())
with check (user_a = auth.uid() or user_b = auth.uid());

-- kioscos
drop policy if exists "Anyone authenticated can view kioscos" on public.kioscos;
create policy "Anyone authenticated can view kioscos"
on public.kioscos
for select
to authenticated
using (true);

-- intercambios
drop policy if exists "Users can view intercambios from their matches" on public.intercambios;
create policy "Users can view intercambios from their matches"
on public.intercambios
for select
to authenticated
using (
	exists (
		select 1
		from public.matches m
		where m.id = intercambios.match_id
			and (m.user_a = auth.uid() or m.user_b = auth.uid())
	)
);

drop policy if exists "Users can create intercambios from their matches" on public.intercambios;
create policy "Users can create intercambios from their matches"
on public.intercambios
for insert
to authenticated
with check (
	exists (
		select 1
		from public.matches m
		where m.id = intercambios.match_id
			and (m.user_a = auth.uid() or m.user_b = auth.uid())
	)
);

drop policy if exists "Users can update intercambios from their matches" on public.intercambios;
create policy "Users can update intercambios from their matches"
on public.intercambios
for update
to authenticated
using (
	exists (
		select 1
		from public.matches m
		where m.id = intercambios.match_id
			and (m.user_a = auth.uid() or m.user_b = auth.uid())
	)
)
with check (
	exists (
		select 1
		from public.matches m
		where m.id = intercambios.match_id
			and (m.user_a = auth.uid() or m.user_b = auth.uid())
	)
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
create index if not exists idx_figuritas_user_id on public.figuritas(user_id);
create index if not exists idx_figuritas_numero on public.figuritas(numero);
create index if not exists idx_matches_user_a on public.matches(user_a);
create index if not exists idx_matches_user_b on public.matches(user_b);
create index if not exists idx_intercambios_match_id on public.intercambios(match_id);
create index if not exists idx_intercambios_kiosco_id on public.intercambios(kiosco_id);

-- ---------------------------------------------------------------------------
-- MVP seed for kioscos (Catamarca)
-- ---------------------------------------------------------------------------
insert into public.kioscos (nombre, direccion, latitud, longitud, activo)
values
	('Kiosco San Cayetano', 'Av. Virgen del Valle 350, San Fernando del Valle', -28.4686, -65.7795, true),
	('Kiosco La Esquina', 'Salta 920, San Fernando del Valle', -28.4699, -65.7859, true),
	('Kiosco Plaza', 'Rivadavia 650, San Fernando del Valle', -28.4662, -65.7791, true)
on conflict do nothing;

-- ---------------------------------------------------------------------------
-- Storage bucket for cached player photos
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'jugadores',
  'jugadores',
  true,
  5242880,
  array['image/png', 'image/jpeg', 'image/webp']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can read jugadores images" on storage.objects;
create policy "Public can read jugadores images"
on storage.objects
for select
to public
using (bucket_id = 'jugadores');

drop policy if exists "Authenticated users can upload jugadores images" on storage.objects;
create policy "Authenticated users can upload jugadores images"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'jugadores');

-- ---------------------------------------------------------------------------
-- Match-making logic RPCs
-- ---------------------------------------------------------------------------

-- 1. find_potential_matches
create or replace function public.find_potential_matches()
returns table (
	id text,
	user_name text,
	avatar_url text,
	reputation integer,
	trades_count integer,
	offered_number integer,
	offered_name text,
	offered_image_url text,
	requested_number integer,
	requested_name text,
	requested_image_url text,
	distance text,
	kiosco_id bigint,
	kiosco_nombre text,
	kiosco_direccion text,
	barrio text,
	figurita_mia_id uuid,
	figurita_ajena_id uuid
)
language sql
security definer
set search_path = public
as $$
	select 
		'pot_' || f_mia_rep.id || '_' || f_ajena_rep.id as id,
		p.nombre as user_name,
		'https://ui-avatars.com/api/?name=' || replace(p.nombre, ' ', '+') as avatar_url,
		p.reputacion as reputation,
		0 as trades_count,
		f_ajena_rep.numero as offered_number,
		f_ajena_rep.nombre_jugador as offered_name,
		f_ajena_rep.imagen_url as offered_image_url,
		f_mia_rep.numero as requested_number,
		f_mia_rep.nombre_jugador as requested_name,
		f_mia_rep.imagen_url as requested_image_url,
		'Kiosco a calcular' as distance,
		1 as kiosco_id,
		'Kiosco por asignar' as kiosco_nombre,
		'Dirección pendiente' as kiosco_direccion,
		'Barrio pendiente' as barrio,
		f_mia_rep.id as figurita_mia_id,
		f_ajena_rep.id as figurita_ajena_id
	from public.figuritas f_mia_rep
	join public.figuritas f_ajena_fal on f_ajena_fal.numero = f_mia_rep.numero
	join public.figuritas f_mia_fal on 1=1
	join public.figuritas f_ajena_rep on f_ajena_rep.numero = f_mia_fal.numero and f_ajena_rep.user_id = f_ajena_fal.user_id
	join public.profiles p on p.id = f_ajena_rep.user_id
	where f_mia_rep.user_id = auth.uid() 
	  and f_mia_rep.tipo = 'repetida'
	  and f_ajena_fal.tipo = 'faltante'
	  and f_mia_fal.user_id = auth.uid()
	  and f_mia_fal.tipo = 'faltante'
	  and f_ajena_rep.tipo = 'repetida'
	  and f_mia_rep.user_id <> f_ajena_rep.user_id;
$$;

revoke all on function public.find_potential_matches() from public;
grant execute on function public.find_potential_matches() to authenticated;

-- 2. create_match_request
create or replace function public.create_match_request(
	p_figurita_mia_id uuid,
	p_figurita_ajena_id uuid
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
	v_user_b uuid;
	v_match_id bigint;
begin
	select user_id into v_user_b
	from public.figuritas
	where id = p_figurita_ajena_id;

	if v_user_b is null then
		raise exception 'Figurita ajena no encontrada';
	end if;

	insert into public.matches (user_a, user_b, figurita_a_id, figurita_b_id, tipo, estado)
	values (auth.uid(), v_user_b, p_figurita_mia_id, p_figurita_ajena_id, 'doble', 'pendiente')
	returning id into v_match_id;

	return v_match_id;
end;
$$;

revoke all on function public.create_match_request(uuid, uuid) from public;
grant execute on function public.create_match_request(uuid, uuid) to authenticated;